#!/usr/bin/env bash
# Configures an Ubuntu server so that:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

# Update localhost: replace 127.0.0.1 with 127.0.0.2
sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2\tlocalhost/' /etc/hosts

# Add or update facebook.com entry
if grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+[[:space:]]+facebook\.com' /etc/hosts; then
    sed -i 's/^[0-9.]\+[[:space:]]\+facebook\.com.*/8.8.8.8\tfacebook.com/' /etc/hosts
else
    echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
fi
